spring.application.name=WhisperVault
server.port=8080

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://root:VIUGA7TD3C0pMD6DKrZ3VKT9JHlLefpD@dpg-d3626533fgac73d72tv0-a.oregon-postgres.render.com/forum_dbms
spring.datasource.username=root
spring.datasource.password=VIUGA7TD3C0pMD6DKrZ3VKT9JHlLefpD
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
